// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKcQqr_w_fJC9Low4QKsUBkhy-iPPqcDo',
    appId: '1:911365036593:web:72d0f52030bb4101fe5310',
    messagingSenderId: '911365036593',
    projectId: 'task-manager-4a380',
    authDomain: 'task-manager-4a380.firebaseapp.com',
    storageBucket: 'task-manager-4a380.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVp58sy551vQUM3A0rxiwobCDyOoFW9LU',
    appId: '1:911365036593:android:3e53eb5c5d21fe4bfe5310',
    messagingSenderId: '911365036593',
    projectId: 'task-manager-4a380',
    storageBucket: 'task-manager-4a380.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfwi5cgM4iBaYhpQIqZh0K-Pwjg0QSUI8',
    appId: '1:911365036593:ios:5132591003304b6dfe5310',
    messagingSenderId: '911365036593',
    projectId: 'task-manager-4a380',
    storageBucket: 'task-manager-4a380.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfwi5cgM4iBaYhpQIqZh0K-Pwjg0QSUI8',
    appId: '1:911365036593:ios:5132591003304b6dfe5310',
    messagingSenderId: '911365036593',
    projectId: 'task-manager-4a380',
    storageBucket: 'task-manager-4a380.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKcQqr_w_fJC9Low4QKsUBkhy-iPPqcDo',
    appId: '1:911365036593:web:cace0bca162a9d23fe5310',
    messagingSenderId: '911365036593',
    projectId: 'task-manager-4a380',
    authDomain: 'task-manager-4a380.firebaseapp.com',
    storageBucket: 'task-manager-4a380.firebasestorage.app',
  );
}
